### ISSUE TITLE
`next export` is not able to work with this setup

### ISSUE THREAD

**Issue by fchengpc** [ooade/next-react-toolbox#5]
when i try to export this is the error i got. any help would be helpful.
```/icon/theme.css:1
(function (exports, require, module, __filename, __dirname) { :root {
                                                                                                       ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (../../../../../../index.js:20:14)```

**Comment by Developerayo** [comment]
Send in your Webpack configuration @fchengpc

**Comment by fchengpc** [comment]
got it working with try catch.
